name: Lint

on:
    push:
      branches:
        - '*'
        - '*/*'
        - '**' 
    pull_request:
      branches:
        - '*'
        - '*/*'
        - '**' 
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm i

      - name: Lint
        run: npm run lint